#!/bin/bash

#-----------
# Configurations
#-----------

APACHE_SITES_ENABLED_DIR=${APACHE_SITES_ENABLED_DIR-/etc/apache2/sites-enabled}
APACHE_SITES_AVAILABLE_DIR=${APACHE_SITES_AVAILABLE_DIR-/etc/apache2/sites-available}
APACHE_LOG_DIR=${APACHE_LOG_DIR-/var/log/apache2}
APACHE_HTTP_PORT=${APACHE_HTTP_PORT-80}
APACHE_SSL_PORT=${APACHE_SSL_PORT-443}
APACHE_APPS_DIR=${APACHE_APPS_DIR-/var/apps}

APACHE_INCLUDE_PHP=${APACHE_INCLUDE_PHP-true}
APACHE_INCLUDE_MYSQL=${APACHE_INCLUDE_MYSQL-true}

DOCKER_SUPPORT_LXC=${DOCKER_SUPPORT_LXC-false}

#-----------
# Install Script
#-----------

echo "Install apache..."

mkdir -p /var/apps/apache
mkdir -p /var/apps/apache/startup.d
mkdir -p $APACHE_SITES_ENABLED_DIR $APACHE_SITES_AVAILABLE_DIR

chown -R www-data:www-data $APACHE_SITES_ENABLED_DIR
chown -R www-data:www-data $APACHE_SITES_AVAILABLE_DIR
cp ./submodules/apache/files/apache.dockerfile /var/apps/apache/Dockerfile

printf '#!/bin/bash\n# Do nothing\n' > /var/apps/apache/startup.d/empty
chmod 755 /var/apps/apache/startup.d/empty

if [[ "$APACHE_INCLUDE_PHP" = true ]]; then
  echo "  -- enabling php"
  sed -i 's|# @PHP_INSTALL@|cat ./submodules/apache/files/php_partial.dockerfile|e' /var/apps/apache/Dockerfile
fi

if [[ "$APACHE_INCLUDE_MYSQL" = true ]]; then
  echo "  -- enabling mysql"
  sed -i 's|# @MYSQL_INSTALL@|cat ./submodules/apache/files/mysql_partial.dockerfile|e' /var/apps/apache/Dockerfile
fi

(cd /var/apps/apache && docker build -t apache .)

if [[ "$DOCKER_SUPPORT_LXC" == true ]]; then
  echo "  -- enabling LXC support"
  cp ./submodules/apache/files/console /var/apps/apache/console
  chmod 755 /var/apps/apache/console
fi

printf "%b" "#!/bin/bash
docker run -i -t \\
  -p 9999:80 \\
  -p 9998:443 \\
  -v $APACHE_APPS_DIR:/var/apps \\
  -v $APACHE_SITES_ENABLED_DIR:/etc/apache2/sites-enabled \\
  -v $APACHE_SITES_AVAILABLE_DIR:/etc/apache2/sites-available \\
  -v $APACHE_LOG_DIR:/var/log/apache2 \\
  apache /bin/bash" > /var/apps/apache/debug

printf "%b" "#!/bin/bash
docker rm apache > /dev/num
docker run -d -t \\
  -p $APACHE_HTTP_PORT:80 \\
  -p $APACHE_SSL_PORT:443 \\
  -v $APACHE_APPS_DIR:/var/apps \\
  -v $APACHE_SITES_ENABLED_DIR:/etc/apache2/sites-enabled \\
  -v $APACHE_SITES_AVAILABLE_DIR:/etc/apache2/sites-available \\
  -v $APACHE_LOG_DIR:/var/log/apache2 \\
  --name apache \\
  apache" > /var/apps/apache/start

NAME=apache DIR=/var/apps/apache ./submodules/docker/stop
NAME=apache DIR=/var/apps/apache ./submodules/docker/idempot

chmod 755 /var/apps/apache/start
chmod 755 /var/apps/apache/debug
