#!/bin/bash

#-----------
# Configurations
#-----------

APACHE_SITES_ENABLED_DIR=${APACHE_SITES_ENABLED_DIR-/etc/apache2/sites-enabled}
APACHE_SITES_AVAILABLE_DIR=${APACHE_SITES_AVAILABLE_DIR-/etc/apache2/sites-available}
APACHE_LOG_DIR=${APACHE_LOG_DIR-/var/log/apache2}
APACHE_HTTP_PORT=${APACHE_HTTP_PORT-80}
APACHE_SSL_PORT=${APACHE_SSL_PORT-443}
APACHE_APPS_DIR=${APACHE_APPS_DIR-/var/local/apps}
APACHE_INCLUDE_RELOAD=${APACHE_INCLUDE_RELOAD-true}
APACHE_LAUNCHER_DIR=${APACHE_LAUNCHER_DIR-/var/local/apache}

APACHE_INCLUDE_PHP=${APACHE_INCLUDE_PHP-true}
APACHE_INCLUDE_MYSQL=${APACHE_INCLUDE_MYSQL-true}

DOCKER_SUPPORT_LXC=${DOCKER_SUPPORT_LXC-false}

#-----------
# Install Script
#-----------

echo "Install apache..."

mkdir -p $APACHE_LAUNCHER_DIR/files
mkdir -p $APACHE_LAUNCHER_DIR/startup.d
mkdir -p $APACHE_SITES_ENABLED_DIR $APACHE_SITES_AVAILABLE_DIR

chown -R www-data:www-data $APACHE_SITES_ENABLED_DIR
chown -R www-data:www-data $APACHE_SITES_AVAILABLE_DIR

cp ./bits/apache/files/apache.dockerfile ${APACHE_LAUNCHER_DIR}/Dockerfile

if [[ ! -e $APACHE_LAUNCHER_DIR/files/do_nothing ]]; then
  printf '#!/bin/bash\n# Do nothing\n' > $APACHE_LAUNCHER_DIR/files/do_nothing
  chmod 755 $APACHE_LAUNCHER_DIR/files/do_nothing
fi

if [[ "$APACHE_INCLUDE_PHP" = true ]]; then
  echo "  -- enabling php"
  sed -i 's|# @PHP_INSTALL@|cat ./bits/apache/files/php_partial.dockerfile|e' ${APACHE_LAUNCHER_DIR}/Dockerfile
fi

if [[ "$APACHE_INCLUDE_MYSQL" = true ]]; then
  echo "  -- enabling mysql"
  sed -i 's|# @MYSQL_INSTALL@|cat ./bits/apache/files/mysql_partial.dockerfile|e' ${APACHE_LAUNCHER_DIR}/Dockerfile
fi

if [[ "$APACHE_INCLUDE_RELOAD" = true ]]; then
  echo "  -- enabling apache reload"
  cp ./bits/apache/files/apache_touch $APACHE_LAUNCHER_DIR/files/apache_touch
  cp ./bits/apache/files/touchandgo $APACHE_LAUNCHER_DIR/files/touchandgo
  cp ./bits/apache/files/apache_reload $APACHE_LAUNCHER_DIR/files/apache_reload
  sed -i 's|# @RELOAD_INSTALL@|cat ./bits/apache/files/reload_partial.dockerfile|e' $APACHE_LAUNCHER_DIR/Dockerfile
fi

(cd $APACHE_LAUNCHER_DIR && docker build -t apache .)

if [[ "$DOCKER_SUPPORT_LXC" == true ]]; then
  echo "  -- enabling LXC support"
  cp ./bits/apache/files/console ${APACHE_LAUNCHER_DIR}/console
  chmod 755 ${APACHE_LAUNCHER_DIR}/console
fi

printf "%b" "#!/bin/bash
docker run -i -t \\
  -p 9999:80 \\
  -p 9998:443 \\
  -v $APACHE_APPS_DIR:/data \\
  -v $APACHE_SITES_ENABLED_DIR:/etc/apache2/sites-enabled \\
  -v $APACHE_SITES_AVAILABLE_DIR:/etc/apache2/sites-available \\
  -v $APACHE_LOG_DIR:/var/log/apache2 \\
  apache /bin/bash" > ${APACHE_LAUNCHER_DIR}/debug

printf "%b" "#!/bin/bash
docker rm apache > /dev/num
docker run -d -t \\
  -p $APACHE_HTTP_PORT:80 \\
  -p $APACHE_SSL_PORT:443 \\
  -v $APACHE_APPS_DIR:/data \\
  -v $APACHE_SITES_ENABLED_DIR:/etc/apache2/sites-enabled \\
  -v $APACHE_SITES_AVAILABLE_DIR:/etc/apache2/sites-available \\
  -v $APACHE_LOG_DIR:/var/log/apache2 \\
  --name apache \\
  apache" > $APACHE_LAUNCHER_DIR/start

NAME=apache DIR=$APACHE_LAUNCHER_DIR ./bits/docker/stop
NAME=apache DIR=$APACHE_LAUNCHER_DIR ./bits/docker/idempot

chmod 755 $APACHE_LAUNCHER_DIR/start
chmod 755 $APACHE_LAUNCHER_DIR/debug

echo "DONE, Install apache."